blank_issues_enabled: false
contact_links:
  - name: We have moved to Linear!
    url: https://linear.app/a8c/team/PAY/new?template=e036ac14-e688-4853-b584-0a476b33e58f
    about: Please open new issues on Linear. If you don't have access to Linear and you want to report an issue, please reach out via Slack.